services:
  - type: web
    name: url-shortener-server
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: BASE_URL
        sync: false
